
'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/biometic.glb -o ./src/app/models/Biometic.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BiometricModel(props) {
  const { nodes, materials } = useGLTF('/models/biometic.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.756, -0.016, -1.095]} rotation={[-Math.PI / 2, 0, 0]} scale={1.653}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.001']} position={[0.562, -0.697, -0.014]} />
          </group>
          <group position={[190, 60, 100]} rotation={[Math.PI, 0, Math.PI]} scale={4}>
            <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials['Material.001']} position={[0, 0, 0.16]} />
          </group>
          <group position={[190, 40, 100]} rotation={[Math.PI, 0, Math.PI]} scale={4}>
            <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials['Material.001']} position={[0, 0, 0.16]} />
          </group>
          <group rotation={[Math.PI, 0, 0]} scale={20}>
            <mesh geometry={nodes.Cylinder002_Material_0.geometry} material={materials['Material.001']} position={[10, -2.9, -4.25]} />
          </group>
          <group position={[0, -20, 0]} rotation={[Math.PI, 0, 0]} scale={20}>
            <mesh geometry={nodes.Cylinder003_Material_0.geometry} material={materials['Material.001']} position={[10, -2.9, -4.25]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/biometic.glb')
