/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/biometic.glb -O ./app/models 
Author: Haikal Nagib (https://sketchfab.com/nagibsy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fingerprint-26164d8f8856432199e664d6245ab20b
Title: fingerprint
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BiometricModel(props) {
  const { nodes, materials } = useGLTF('/models/biometic.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials.Material} position={[190, 60, 100]} rotation={[-Math.PI, 0, -Math.PI]} scale={4} />
        <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} position={[190, 40, 100]} rotation={[-Math.PI, 0, -Math.PI]} scale={4} />
        <mesh geometry={nodes.Cylinder002_Material_0.geometry} material={materials.Material} rotation={[Math.PI, 0, 0]} scale={20} />
        <mesh geometry={nodes.Cylinder003_Material_0.geometry} material={materials.Material} position={[0, -20, 0]} rotation={[Math.PI, 0, 0]} scale={20} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/biometic.glb')
