/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/camera.glb -O ./app/models 
Author: Danylo Tyupa (https://sketchfab.com/danzl0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/security-camera-e0657ce75f374f1e911e00f710046572
Title: Security camera
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CameraModel(props) {
  const { nodes, materials } = useGLTF('/models/camera.glb')
  return (
    <group {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/camera.glb')
