/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/cpu.glb -o ./src/app/models/Cpu.jsx 
Author: Lutvi Angreani (https://sketchfab.com/lutviangreani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cpu-3f1c1b10c8ca446a90435b5da8d06926
Title: Cpu
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CpuModel(props) {
  const { nodes, materials } = useGLTF('/models/cpu.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material} position={[-0.236, -0.138, 0.191]} rotation={[-Math.PI / 2, 0, -2.562]} scale={0.012} />
    </group>
  )
}

useGLTF.preload('/models/cpu.glb')
