/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/dvd.glb -o ./src/app/models/Dvd.jsx 
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dvd-player-from-poly-by-google-6e340572f05048dfbf3444c4d237088b
Title: Dvd player from Poly by Google
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DvdModel(props) {
  const { nodes, materials } = useGLTF('/models/dvd.glb')
  return (
    <group {...props} dispose={null} scale={.04}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['01___Default']} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['03___Default']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['04___Default']} />
    </group>
  )
}

useGLTF.preload('/models/dvd.glb')
