/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/hub.glb -o ./src/app/models/Hub.jsx 
Author: arieffitrah (https://sketchfab.com/arieffitrah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tl-sf1005d-90966bd409204294918c68c11c7da831
Title: TL-SF1005D
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HubModel(props) {
  const { nodes, materials } = useGLTF('/models/hub.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-3.067, 0.102, 0.008]} scale={[0.502, 0.502, 0.335]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Black} />
      </group>
      <group position={[-3.072, 0.091, 0.334]} scale={[0.502, 0.502, 0.335]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Lamp} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-3.072, 0.083, 0.327]} scale={[0.366, 0.502, 0.288]}>
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[-2.633, 0.107, -0.125]} rotation={[0, 0, -Math.PI / 2]} scale={[0.002, 0.038, 0.002]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Lamp} position={[-3.425, 0.213, -0.244]} scale={[0.057, 0.021, 0.006]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Lamp} position={[-3.285, 0.213, -0.244]} scale={[0.015, 0.021, 0.006]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Material.004']} position={[-2.795, 0.032, 0.368]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.004']} position={[-2.936, 0.032, 0.368]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
      <mesh geometry={nodes.Object_23.geometry} material={materials['Material.004']} position={[-3.076, 0.032, 0.368]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.004']} position={[-3.215, 0.032, 0.368]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['Material.004']} position={[-3.358, 0.032, 0.368]} rotation={[Math.PI / 2, 0, 0]} scale={0.041} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[-3.224, 0.215, -0.258]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.018} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[-3.254, 0.215, -0.258]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.018} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} position={[-3.285, 0.215, -0.258]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.018} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[-3.315, 0.215, -0.258]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.018} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material_0} position={[-3.345, 0.215, -0.258]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.018} />
    </group>
  )
}

useGLTF.preload('/models/hub.glb')
