/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/keyboard.glb -o ./src/app/models/KeyBoard.jsx 
Author: FelikinRuslan (https://sketchfab.com/FelikinRuslan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-1ba4055c33674567b51b783701ed05ce
Title: Mechanical keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyBoardModel(props) {
  const { nodes, materials } = useGLTF('/models/keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.619, -0.017]} rotation={[0.123, 0, 0]}>
        <mesh geometry={nodes.keyboard_Keyboard_0.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.keyboard_Key_0.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes.keys_Key_0.geometry} material={materials.material} position={[-15.094, 1.498, 2.822]} rotation={[0.123, 0, 0]} />
      <mesh geometry={nodes.legs_Keyboard_0.geometry} material={materials.Keyboard} position={[0, 0.921, -4.98]} rotation={[2.487, 0, 0]} />
      <mesh geometry={nodes.wire_Keyboard_0.geometry} material={materials.Keyboard} position={[0.008, 2.05, -6.444]} rotation={[0.123, 0, 0]} />
      <mesh geometry={nodes.usb_Keyboard_0.geometry} material={materials.Keyboard} position={[-3.918, 0.363, -46.929]} rotation={[-0.024, 0, 0]} />
      <mesh geometry={nodes.emissive_Key_0.geometry} material={materials.material} position={[-15.094, 1.671, 2.843]} rotation={[0.123, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/keyboard.glb')
