/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/lan.glb -o ./src/app/models/Lan.jsx 
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/router-93c561886acc48bab5a34d02f0a463e5
Title: Router
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LanModel(props) {
  const { nodes, materials } = useGLTF('/models/lan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['01_-_Default']} position={[0, 3.55, 9.499]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['01_-_Default']} position={[-9.413, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['01_-_Default']} position={[9.413, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['01_-_Default']} position={[7.907, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['01_-_Default']} position={[6.268, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials['01_-_Default']} position={[4.71, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['01_-_Default']} position={[3.139, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['01_-_Default']} position={[1.573, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['01_-_Default']} position={[0.005, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials['01_-_Default']} position={[-1.577, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials['01_-_Default']} position={[-3.14, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials['01_-_Default']} position={[-4.715, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['01_-_Default']} position={[-6.286, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials['01_-_Default']} position={[-7.866, 3.465, 9.497]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['01_-_Default']} position={[4.206, 1.299, 9.117]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/lan.glb')
