/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/monitor.glb -o ./src/app/models/Monitor.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MonitorModel(props) {
  const { nodes, materials } = useGLTF('/models/monitor.glb')
  return (
    <group {...props} dispose={null} position={[0, -10, 0]} scale={.05}>
      <group position={[0, 14.702, 52.536]} rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.926}>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1001__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1002__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1003__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1004__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1005__0024_OrangeRed_0.geometry} material={materials['0024_OrangeRed']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1006__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1007_Material001_0.geometry} material={materials['Material.001']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1008__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1009__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1010__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1011__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1012__0136_Charcoal_0.geometry} material={materials['0136_Charcoal']} position={[188.718, 25.015, -4.998]} />
            </group>
            <group position={[35.239, -25.015, -57.676]}>
              <mesh geometry={nodes.group_1013_Material001_0.geometry} material={materials['Material.001']} position={[188.718, 25.015, -4.998]} />
            </group>
            <mesh geometry={nodes.group_2006_Material002_0.geometry} material={materials['Material.002']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2_Material003_0.geometry} material={materials['Material.003']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2001__0024_OrangeRed_0.geometry} material={materials['0024_OrangeRed']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2002__0024_OrangeRed_0.geometry} material={materials['0024_OrangeRed']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2003_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2004_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2005_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2007_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2008_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
            <mesh geometry={nodes.group_2009_Material001_0.geometry} material={materials['Material.001']} position={[223.958, 0, -62.674]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/monitor.glb')
