/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/mouse.glb -o ./src/app/models/Mouse.jsx 
Author: rubykamen (https://sketchfab.com/rubykamen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pc-mouse-type-r-b782768a5ec1453fb2587bd9d82aaf7e
Title: PC Mouse type-R
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MouseModel(props) {
  const { nodes, materials } = useGLTF('/models/mouse.glb')
  return (
    <group {...props} dispose={null} scale={0.4}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.R_Mouse_00_R_Mouse_0.geometry} material={materials.R_Mouse} position={[0, 3.403, 0.868]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mouse.glb')
