/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/newmobile.glb -o ./src/app/models/NewMobile.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NewMobileModel(props) {
  const { nodes, materials } = useGLTF('/models/newmobile.glb')
  return (
    <group {...props} dispose={null} scale={1.6}>
      <group position={[0, -1.554, 0]} rotation={[Math.PI / 2, 0, 0]} scale={19.078}>
        <mesh geometry={nodes.back_details.geometry} material={materials.back_details} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.back_details_filledRings.geometry} material={materials.back_cover_thickness} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.back_details_glass.geometry} material={materials.glass} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.back_inside.geometry} material={materials.back_inside} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.backCover.geometry} material={materials.back_cover} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.backCover_camera.geometry} material={materials.back_cover_thickness} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.camera_front.geometry} material={materials.cameras} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.camera_front_glass.geometry} material={materials.cameras_lense} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.frame_plastic.geometry} material={materials.frame} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.frame_plastic_border.geometry} material={materials.frame_border} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.frontScreen.geometry} material={materials.glass} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.glass_cover.geometry} material={materials.glass} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lens_edge.geometry} material={materials.lens_edge} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lens_edge_cover.geometry} material={materials.lens_edge_cover} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lense_house.geometry} material={materials.lens_edge} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lense_house_edge.geometry} material={materials.lens_edge_cover} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lense_inner.geometry} material={materials.cameras} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.lenses.geometry} material={materials.cameras_lense} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.on_off_switch.geometry} material={materials.switches} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.screen.geometry} material={materials.screen} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.sim_tray.geometry} material={materials.frame} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.usb_c.geometry} material={materials.usbc} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.volume_down.geometry} material={materials.switches} position={[0, 0, -0.081]} />
        <mesh geometry={nodes.volume_up.geometry} material={materials.switches} position={[0, 0, -0.081]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/newmobile.glb')
