/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/newmobile.glb -o ./src/app/models/NewMobile.jsx 
Author: Matt Gilchrist (https://sketchfab.com/MattGilchrist)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cell-phone-793b092deff04d9fae3a368230bbc06f
Title: Cell Phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NewMobileModel(props) {
  const { nodes, materials } = useGLTF('/models/newmobile.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.HomeButton_PhoneButtons_m_0.geometry} material={materials.PhoneButtons_m} position={[0, -1.322, -0.02]} />
      <mesh geometry={nodes.PhoneBody_PhoneBody_m_0.geometry} material={materials.PhoneBody_m} />
      <mesh geometry={nodes.PhoneBody_PhoneScreen_M_0.geometry} material={materials.PhoneScreen_M} />
      <mesh geometry={nodes.PowerButton_PhoneButtons_m_0.geometry} material={materials.PhoneButtons_m} position={[-0.723, 1.487, 0.008]} />
      <mesh geometry={nodes.VolumeButton_PhoneButtons_m_0.geometry} material={materials.PhoneButtons_m} position={[0.749, 1.145, 0.008]} rotation={[0, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/models/newmobile.glb')
