/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/oldmobile.glb -o ./src/app/models/OldMouse.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OldMobileModel(props) {
  const { nodes, materials } = useGLTF('/models/oldmobile.glb')
  return (
    <group {...props} dispose={null} scale={.12}>
      <group position={[7.28, 1.092, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.078}>
        <group position={[-89.008, -25.512, 0]} scale={[44.74, 21.863, 44.74]}>
          <mesh geometry={nodes.Cube_back_0.geometry} material={materials.back} position={[-0.109, 0, 0.256]} />
          <mesh geometry={nodes.Cube_screen_0.geometry} material={materials.screen} position={[-0.109, 0, 0.256]} />
          <mesh geometry={nodes.Cube_side_0.geometry} material={materials.side} position={[-0.109, 0, 0.256]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/oldmobile.glb')
