/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/oldmobile.glb -o ./src/app/models/OldMobile.jsx 
Author: KI NG (https://sketchfab.com/dadybandit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-nokia-phone-low-poly-a022864ae7b642a39469652c3eda2b9a
Title: old nokia phone low poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OldMobileModel(props) {
  const { nodes, materials } = useGLTF('/models/oldmobile.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-89.008, -25.512, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.74, 21.863, 44.74]}>
        <mesh geometry={nodes.Cube_back_0.geometry} material={materials.back} />
        <mesh geometry={nodes.Cube_side_0.geometry} material={materials.side} />
        <mesh geometry={nodes.Cube_screen_0.geometry} material={materials.screen} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/oldmobile.glb')
