/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/printer.glb -o ./src/app/models/Printer.jsx 
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/inkjet-printer-and-scanner-ecb6f40c66ff4307a3eadb67cabc83dc
Title: Inkjet printer and scanner
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PrinterModel(props) {
  const { nodes, materials } = useGLTF('/models/printer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.semitrans} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['black-textured']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/printer.glb')
