/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/projector.glb -o ./src/app/models/Projector.jsx 
Author: 1-3D.com (https://sketchfab.com/1-3D.com)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/video-projector-e14a2b9336df47a6b536a3a1cf829221
Title: Video projector
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ProjectorModel(props) {
  const { nodes, materials } = useGLTF('/models/projector.glb')
  return (
    <group {...props} dispose={null} scale={.1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.foot} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.projector} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/projector.glb')
