/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/scanner2.glb -o ./src/app/models/Scanner2.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scanner2Model(props) {
  const { nodes, materials } = useGLTF('/models/scanner2.glb')
  return (
    <group {...props} dispose={null} scale={.06}>
      <group position={[0, -4.674, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.67}>
        <group scale={100}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.Printer} position={[0, 0, 0.028]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scanner2.glb')
