/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/scanner.glb -o ./src/app/models/Scanner.jsx 
Author: satpute.trupti (https://sketchfab.com/satpute.trupti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scanner-7b04a301630747a0a96786f88d2d4905
Title: scanner
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ScannerModel(props) {
  const { nodes, materials } = useGLTF('/models/scanner.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['default']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['default']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['default']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/scanner.glb')
