/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/scanner.glb -o ./src/app/models/Scanner.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ScannerModel(props) {
  const { nodes, materials } = useGLTF('/models/scanner.glb')
  return (
    <group {...props} dispose={null} scale={.1} position={[0, -1, 0]}>
      <mesh geometry={nodes.button.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} scale={0.434} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.434}>
        <mesh geometry={nodes.monitor_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.monitor_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.scanner.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.434} />
      <mesh geometry={nodes.stand.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} scale={0.434} />
    </group>
  )
}

useGLTF.preload('/models/scanner.glb')
