/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/telephone.glb -o ./src/app/models/Telephone.jsx 
Author: alixor22 (https://sketchfab.com/alixor22)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/landline-phone-85d3fe01f51642d6b3130e602d6633fa
Title: Landline phone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TelephoneModel(props) {
  const { nodes, materials } = useGLTF('/models/telephone.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.tel_fijo_tel_fijo_0.geometry} material={materials.tel_fijo} rotation={[-1.489, 0, 0]} scale={[6.504, 9.088, 6.504]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/telephone.glb')
