/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public\ring.glb 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-pulse-de9589edeaf940378e593f712fb84018
Title: Cyber Pulse
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function AvatarModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ring.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    actions.Animation.play()
  })
  useFrame((state , delta)=>{
    group.current.rotation.x += delta * 0.05
    group.current.rotation.y += delta * 0.05
    group.current.rotation.z += delta * 0.05
  })
  return (
    <group ref={group} {...props} args={[4,4,4]} dispose={null} scale={1.2}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Torus002_0" position={[3.363, 0, 0]} scale={1.077}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.material} />
              </group>
              <group name="Torus003_1" position={[3.363, 0, 0]} scale={0.94}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material} />
              </group>
              <group name="Torus004_2" position={[3.363, 0, 0.053]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material} />
              </group>
              <group name="Torus005_3" position={[3.363, 0, -0.044]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material} />
              </group>
              <group name="Torus006_4" position={[3.363, 0, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_1} />
              </group>
              <group name="Torus007_5" position={[3.363, 0, 0]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_1} />
              </group>
              <group name="Torus008_6" position={[3.363, 0, 0]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_1} />
              </group>
              <group name="Torus009_7" position={[3.363, 0, 0]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_1} />
              </group>
              <group name="Torus001_14" position={[-3.363, 0, 0]}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.material} />
              </group>
              <group name="Torus010_15" position={[-3.363, 0, 0]}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.material} />
              </group>
              <group name="Torus012_16" position={[-3.363, 0, 0]}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.material} />
              </group>
              <group name="Torus013_17" position={[-3.363, 0, 0]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.material} />
              </group>
              <group name="Torus014_18" position={[-3.363, 0, 0]} scale={1.077}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material_1} />
              </group>
              <group name="Torus015_19" position={[-3.363, 0, 0]} scale={0.94}>
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.material_1} />
              </group>
              <group name="Torus016_20" position={[-3.363, 0, -0.053]}>
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.material_1} />
              </group>
              <group name="Torus017_21" position={[-3.363, 0, 0.044]}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.material_1} />
              </group>
              <group name="Torus018_27" position={[0, 0, -3.363]} scale={1.077}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material} />
              </group>
              <group name="Torus019_28" position={[0, 0, -3.363]} scale={0.94}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material} />
              </group>
              <group name="Torus020_29" position={[0.053, 0, -3.363]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material} />
              </group>
              <group name="Torus021_30" position={[-0.044, 0, -3.363]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material} />
              </group>
              <group name="Torus022_31" position={[0, 0, -3.363]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_1} />
              </group>
              <group name="Torus023_32" position={[0, 0, -3.363]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_1} />
              </group>
              <group name="Torus024_33" position={[0, 0, -3.363]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_1} />
              </group>
              <group name="Torus025_34" position={[0, 0, -3.363]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_1} />
              </group>
              <group name="Torus026_40" position={[0, 0, 3.363]}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.material} />
              </group>
              <group name="Torus027_41" position={[0, 0, 3.363]}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.material} />
              </group>
              <group name="Torus028_42" position={[0, 0, 3.363]}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.material} />
              </group>
              <group name="Torus029_43" position={[0, 0, 3.363]}>
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.material} />
              </group>
              <group name="Torus030_44" position={[0, 0, 3.363]} scale={1.077}>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.material_1} />
              </group>
              <group name="Torus031_45" position={[0, 0, 3.363]} scale={0.94}>
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.material_1} />
              </group>
              <group name="Torus032_46" position={[-0.053, 0, 3.363]}>
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_1} />
              </group>
              <group name="Torus033_47" position={[0.044, 0, 3.363]}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.material_1} />
              </group>
              <group name="Torus034_53" position={[2.378, 0, 2.378]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material} />
              </group>
              <group name="Torus035_54" position={[2.378, 0, 2.378]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material} />
              </group>
              <group name="Torus036_55" position={[2.378, 0, 2.378]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material} />
              </group>
              <group name="Torus037_56" position={[2.378, 0, 2.378]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material} />
              </group>
              <group name="Torus038_57" position={[2.378, 0, 2.378]} scale={1.077}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_1} />
              </group>
              <group name="Torus039_58" position={[2.378, 0, 2.378]} scale={0.94}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_1} />
              </group>
              <group name="Torus040_59" position={[2.341, 0, 2.416]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_1} />
              </group>
              <group name="Torus041_60" position={[2.409, 0, 2.347]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_1} />
              </group>
              <group name="Torus042_66" position={[-2.378, 0, -2.378]} scale={1.077}>
                <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.material} />
              </group>
              <group name="Torus043_67" position={[-2.378, 0, -2.378]} scale={0.94}>
                <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.material} />
              </group>
              <group name="Torus044_68" position={[-2.341, 0, -2.416]}>
                <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.material} />
              </group>
              <group name="Torus045_69" position={[-2.409, 0, -2.347]}>
                <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.material} />
              </group>
              <group name="Torus046_70" position={[-2.378, 0, -2.378]}>
                <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.material_1} />
              </group>
              <group name="Torus047_71" position={[-2.378, 0, -2.378]}>
                <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.material_1} />
              </group>
              <group name="Torus048_72" position={[-2.378, 0, -2.378]}>
                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.material_1} />
              </group>
              <group name="Torus049_73" position={[-2.378, 0, -2.378]}>
                <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.material_1} />
              </group>
              <group name="Torus050_79" position={[2.378, 0, -2.378]} scale={1.077}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material} />
              </group>
              <group name="Torus051_80" position={[2.378, 0, -2.378]} scale={0.94}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material} />
              </group>
              <group name="Torus052_81" position={[2.416, 0, -2.341]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material} />
              </group>
              <group name="Torus053_82" position={[2.347, 0, -2.409]}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material} />
              </group>
              <group name="Torus054_83" position={[2.378, 0, -2.378]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_1} />
              </group>
              <group name="Torus055_84" position={[2.378, 0, -2.378]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.material_1} />
              </group>
              <group name="Torus056_85" position={[2.378, 0, -2.378]}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.material_1} />
              </group>
              <group name="Torus057_86" position={[2.378, 0, -2.378]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.material_1} />
              </group>
              <group name="Torus058_92" position={[-2.378, 0, 2.378]}>
                <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.material} />
              </group>
              <group name="Torus059_93" position={[-2.378, 0, 2.378]}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.material} />
              </group>
              <group name="Torus060_94" position={[-2.378, 0, 2.378]}>
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.material} />
              </group>
              <group name="Torus061_95" position={[-2.378, 0, 2.378]}>
                <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.material} />
              </group>
              <group name="Torus062_96" position={[-2.378, 0, 2.378]} scale={1.077}>
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.material_1} />
              </group>
              <group name="Torus063_97" position={[-2.378, 0, 2.378]} scale={0.94}>
                <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.material_1} />
              </group>
              <group name="Torus064_98" position={[-2.416, 0, 2.341]}>
                <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.material_1} />
              </group>
              <group name="Torus065_99" position={[-2.347, 0, 2.409]}>
                <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.material_1} />
              </group>
              <group name="Cylinder_105" rotation={[-Math.PI / 2, 0, 0]} scale={0.432}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.material_5} />
              </group>
              <group name="Cylinder001_107" rotation={[-Math.PI / 2, 0, 0]} scale={0.432}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material_6} />
              </group>
              <group name="Torus011_8" scale={1.2}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.MAIN} />
              </group>
              <group name="HOOP001_13" rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                <group name="HOOP_12" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER_11">
                    <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP003_26" rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
                <group name="HOOP002_25" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER001_24">
                    <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP005_39" rotation={[0, 0, -Math.PI / 2]}>
                <group name="HOOP004_38" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER002_37">
                    <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP007_52" rotation={[-Math.PI, 0, Math.PI / 2]}>
                <group name="HOOP006_51" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER003_50">
                    <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP009_65" rotation={[Math.PI, -Math.PI / 4, Math.PI / 2]}>
                <group name="HOOP008_64" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER004_63">
                    <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP011_78" rotation={[0, Math.PI / 4, -Math.PI / 2]}>
                <group name="HOOP010_77" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER005_76">
                    <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP013_91" rotation={[0, -Math.PI / 4, -Math.PI / 2]}>
                <group name="HOOP012_90" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER006_89">
                    <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="HOOP015_104" rotation={[-Math.PI, Math.PI / 4, Math.PI / 2]}>
                <group name="HOOP014_103" position={[0, 0, -3.363]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="COVER007_102">
                    <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.COVER} />
                  </group>
                  <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.hoops} />
                </group>
              </group>
              <group name="Sphere_109" scale={1.7}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.core} />
              </group>
              <group name="Sphere001_110" scale={19.125}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.core} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <shadowMaterial blending={3} blendColor={"pink"}/>
    </group>
  )
}

useGLTF.preload('/ring.glb')
