'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar";
import { AnimatePresence, motion } from "framer-motion";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Tech Savvy</title>
        <meta name="google-site-verification" content="mcomaJmxXoyGe-uuCRa0rp_zqqcST2IID0XeGLjJ3AU" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/logo.png" />
      </head>
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
